# Generated by Django 4.0.2 on 2022-02-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
